// Automatically generated default CSV data
const defaultCsvData = `\
Lecture,Phase,Topic,Class No,Completed,Revision 1,Revision 2,Questions Solved,Weak Topic,Date Completed,Notes
Number System - Class 01,Foundation,Number System,1,False,False,False,,False,,
Number System - Class 02,Foundation,Number System,2,False,False,False,,False,,
Number System - Class 03,Foundation,Number System,3,False,False,False,,False,,
Number System - Class 04,Foundation,Number System,4,False,False,False,,False,,
Number System - Class 05,Foundation,Number System,5,False,False,False,,False,,
Number System - Class 06,Foundation,Number System,6,False,False,False,,False,,
Number System - Class 07,Foundation,Number System,7,False,False,False,,False,,
Number System - Class 08,Foundation,Number System,8,False,False,False,,False,,
Number System - Class 09,Foundation,Number System,9,False,False,False,,False,,
Number System - Class 10,Foundation,Number System,10,False,False,False,,False,,
Number System - Class 11,Foundation,Number System,11,False,False,False,,False,,
Number System - Class 12,Foundation,Number System,12,False,False,False,,False,,
Number System - Class 13,Foundation,Number System,13,False,False,False,,False,,
Number System - Class 14,Foundation,Number System,14,False,False,False,,False,,
Number System - Class 15,Foundation,Number System,15,False,False,False,,False,,
Number System - Class 16,Foundation,Number System,16,False,False,False,,False,,
Number System - Class 17,Foundation,Number System,17,False,False,False,,False,,
Number System - Class 18,Foundation,Number System,18,False,False,False,,False,,
Number System - Class 19,Foundation,Number System,19,False,False,False,,False,,
Number System - Class 20,Foundation,Number System,20,False,False,False,,False,,
Number System - Class 21,Foundation,Number System,21,False,False,False,,False,,
Calculation & Simplification - Class 01,Foundation,Calculation & Simplification,1,False,False,False,,False,,
Calculation & Simplification - Class 02,Foundation,Calculation & Simplification,2,False,False,False,,False,,
Calculation & Simplification - Class 03,Foundation,Calculation & Simplification,3,False,False,False,,False,,
Calculation & Simplification - Class 04,Foundation,Calculation & Simplification,4,False,False,False,,False,,
Calculation & Simplification - Class 05,Foundation,Calculation & Simplification,5,False,False,False,,False,,
Calculation & Simplification - Class 06,Foundation,Calculation & Simplification,6,False,False,False,,False,,
Calculation & Simplification - Class 07,Foundation,Calculation & Simplification,7,False,False,False,,False,,
Calculation & Simplification - Class 08,Foundation,Calculation & Simplification,8,False,False,False,,False,,
Calculation & Simplification - Class 09,Foundation,Calculation & Simplification,9,False,False,False,,False,,
Calculation & Simplification - Class 10,Foundation,Calculation & Simplification,10,False,False,False,,False,,
Calculation & Simplification - Class 11,Foundation,Calculation & Simplification,11,False,False,False,,False,,
Calculation & Simplification - Class 12,Foundation,Calculation & Simplification,12,False,False,False,,False,,
LCM & HCF - Class 01,Foundation,LCM & HCF,1,False,False,False,,False,,
LCM & HCF - Class 02,Foundation,LCM & HCF,2,False,False,False,,False,,
LCM & HCF - Class 03,Foundation,LCM & HCF,3,False,False,False,,False,,
LCM & HCF - Class 04,Foundation,LCM & HCF,4,False,False,False,,False,,
LCM & HCF - Class 05,Foundation,LCM & HCF,5,False,False,False,,False,,
LCM & HCF - Class 06,Foundation,LCM & HCF,6,False,False,False,,False,,
LCM & HCF - Class 07,Foundation,LCM & HCF,7,False,False,False,,False,,
LCM & HCF - Class 08,Foundation,LCM & HCF,8,False,False,False,,False,,
LCM & HCF - Class 09,Foundation,LCM & HCF,9,False,False,False,,False,,
LCM & HCF - Class 10,Foundation,LCM & HCF,10,False,False,False,,False,,
LCM & HCF - Class 11,Foundation,LCM & HCF,11,False,False,False,,False,,
Surds & Indices - Class 01,Foundation,Surds & Indices,1,False,False,False,,False,,
Surds & Indices - Class 02,Foundation,Surds & Indices,2,False,False,False,,False,,
Surds & Indices - Class 03,Foundation,Surds & Indices,3,False,False,False,,False,,
Surds & Indices - Class 04,Foundation,Surds & Indices,4,False,False,False,,False,,
Surds & Indices - Class 05,Foundation,Surds & Indices,5,False,False,False,,False,,
Surds & Indices - Class 06,Foundation,Surds & Indices,6,False,False,False,,False,,
Surds & Indices - Class 07,Foundation,Surds & Indices,7,False,False,False,,False,,
Surds & Indices - Class 08,Foundation,Surds & Indices,8,False,False,False,,False,,
Surds & Indices - Class 09,Foundation,Surds & Indices,9,False,False,False,,False,,
Surds & Indices - Class 10,Foundation,Surds & Indices,10,False,False,False,,False,,
Percentage - Class 01,Foundation,Percentage,1,False,False,False,,False,,
Percentage - Class 02,Foundation,Percentage,2,False,False,False,,False,,
Percentage - Class 03,Foundation,Percentage,3,False,False,False,,False,,
Percentage - Class 04,Foundation,Percentage,4,False,False,False,,False,,
Percentage - Class 05,Foundation,Percentage,5,False,False,False,,False,,
Percentage - Class 06,Foundation,Percentage,6,False,False,False,,False,,
Percentage - Class 07,Foundation,Percentage,7,False,False,False,,False,,
Percentage - Class 08,Foundation,Percentage,8,False,False,False,,False,,
Percentage - Class 09,Foundation,Percentage,9,False,False,False,,False,,
Percentage - Class 10,Foundation,Percentage,10,False,False,False,,False,,
Percentage - Class 11,Foundation,Percentage,11,False,False,False,,False,,
Percentage - Class 12,Foundation,Percentage,12,False,False,False,,False,,
Percentage - Class 13,Foundation,Percentage,13,False,False,False,,False,,
Percentage - Class 14,Foundation,Percentage,14,False,False,False,,False,,
Percentage - Class 15,Foundation,Percentage,15,False,False,False,,False,,
Percentage - Class 16,Foundation,Percentage,16,False,False,False,,False,,
Percentage - Class 17,Foundation,Percentage,17,False,False,False,,False,,
Percentage - Class 18,Foundation,Percentage,18,False,False,False,,False,,
Percentage - Class 19,Foundation,Percentage,19,False,False,False,,False,,
Ratio & Proportion - Class 01,Foundation,Ratio & Proportion,1,False,False,False,,False,,
Ratio & Proportion - Class 02,Foundation,Ratio & Proportion,2,False,False,False,,False,,
Ratio & Proportion - Class 03,Foundation,Ratio & Proportion,3,False,False,False,,False,,
Ratio & Proportion - Class 04,Foundation,Ratio & Proportion,4,False,False,False,,False,,
Ratio & Proportion - Class 05,Foundation,Ratio & Proportion,5,False,False,False,,False,,
Ratio & Proportion - Class 06,Foundation,Ratio & Proportion,6,False,False,False,,False,,
Ratio & Proportion - Class 07,Foundation,Ratio & Proportion,7,False,False,False,,False,,
Ratio & Proportion - Class 08,Foundation,Ratio & Proportion,8,False,False,False,,False,,
Ratio & Proportion - Class 09,Foundation,Ratio & Proportion,9,False,False,False,,False,,
Ratio & Proportion - Class 10,Foundation,Ratio & Proportion,10,False,False,False,,False,,
Ratio & Proportion - Class 11,Foundation,Ratio & Proportion,11,False,False,False,,False,,
Ratio & Proportion - Class 12,Foundation,Ratio & Proportion,12,False,False,False,,False,,
Profit & Loss - Class 01,Arithmetic,Profit & Loss,1,False,False,False,,False,,
Profit & Loss - Class 02,Arithmetic,Profit & Loss,2,False,False,False,,False,,
Profit & Loss - Class 03,Arithmetic,Profit & Loss,3,False,False,False,,False,,
Profit & Loss - Class 04,Arithmetic,Profit & Loss,4,False,False,False,,False,,
Profit & Loss - Class 05,Arithmetic,Profit & Loss,5,False,False,False,,False,,
Profit & Loss - Class 06,Arithmetic,Profit & Loss,6,False,False,False,,False,,
Profit & Loss - Class 07,Arithmetic,Profit & Loss,7,False,False,False,,False,,
Profit & Loss - Class 08,Arithmetic,Profit & Loss,8,False,False,False,,False,,
Profit & Loss - Class 09,Arithmetic,Profit & Loss,9,False,False,False,,False,,
Profit & Loss - Class 10,Arithmetic,Profit & Loss,10,False,False,False,,False,,
Discount - Class 01,Arithmetic,Discount,1,False,False,False,,False,,
Discount - Class 02,Arithmetic,Discount,2,False,False,False,,False,,
Discount - Class 03,Arithmetic,Discount,3,False,False,False,,False,,
Discount - Class 04,Arithmetic,Discount,4,False,False,False,,False,,
Discount - Class 05,Arithmetic,Discount,5,False,False,False,,False,,
Discount - Class 06,Arithmetic,Discount,6,False,False,False,,False,,
Discount - Class 07,Arithmetic,Discount,7,False,False,False,,False,,
Discount - Class 08,Arithmetic,Discount,8,False,False,False,,False,,
Discount - Class 09,Arithmetic,Discount,9,False,False,False,,False,,
Discount - Class 10,Arithmetic,Discount,10,False,False,False,,False,,
Discount - Class 11,Arithmetic,Discount,11,False,False,False,,False,,
Simple & Compound Interest - Class 01,Arithmetic,Simple & Compound Interest,1,False,False,False,,False,,
Simple & Compound Interest - Class 02,Arithmetic,Simple & Compound Interest,2,False,False,False,,False,,
Simple & Compound Interest - Class 03,Arithmetic,Simple & Compound Interest,3,False,False,False,,False,,
Simple & Compound Interest - Class 04,Arithmetic,Simple & Compound Interest,4,False,False,False,,False,,
Simple & Compound Interest - Class 05,Arithmetic,Simple & Compound Interest,5,False,False,False,,False,,
Simple & Compound Interest - Class 06,Arithmetic,Simple & Compound Interest,6,False,False,False,,False,,
Simple & Compound Interest - Class 07,Arithmetic,Simple & Compound Interest,7,False,False,False,,False,,
Simple & Compound Interest - Class 08,Arithmetic,Simple & Compound Interest,8,False,False,False,,False,,
Simple & Compound Interest - Class 09,Arithmetic,Simple & Compound Interest,9,False,False,False,,False,,
Simple & Compound Interest - Class 10,Arithmetic,Simple & Compound Interest,10,False,False,False,,False,,
Simple & Compound Interest - Class 11,Arithmetic,Simple & Compound Interest,11,False,False,False,,False,,
Simple & Compound Interest - Class 12,Arithmetic,Simple & Compound Interest,12,False,False,False,,False,,
Simple & Compound Interest - Class 13,Arithmetic,Simple & Compound Interest,13,False,False,False,,False,,
Simple & Compound Interest - Class 14,Arithmetic,Simple & Compound Interest,14,False,False,False,,False,,
Simple & Compound Interest - Class 15,Arithmetic,Simple & Compound Interest,15,False,False,False,,False,,
Simple & Compound Interest - Class 16,Arithmetic,Simple & Compound Interest,16,False,False,False,,False,,
Simple & Compound Interest - Class 17,Arithmetic,Simple & Compound Interest,17,False,False,False,,False,,
Simple & Compound Interest - Class 18,Arithmetic,Simple & Compound Interest,18,False,False,False,,False,,
Simple & Compound Interest - Class 19,Arithmetic,Simple & Compound Interest,19,False,False,False,,False,,
Simple & Compound Interest - Class 20,Arithmetic,Simple & Compound Interest,20,False,False,False,,False,,
Simple & Compound Interest - Class 21,Arithmetic,Simple & Compound Interest,21,False,False,False,,False,,
Simple & Compound Interest - Class 22,Arithmetic,Simple & Compound Interest,22,False,False,False,,False,,
Simple & Compound Interest - Class 23,Arithmetic,Simple & Compound Interest,23,False,False,False,,False,,
Simple & Compound Interest - Class 24,Arithmetic,Simple & Compound Interest,24,False,False,False,,False,,
Average - Class 01,Arithmetic,Average,1,False,False,False,,False,,
Average - Class 02,Arithmetic,Average,2,False,False,False,,False,,
Average - Class 03,Arithmetic,Average,3,False,False,False,,False,,
Average - Class 04,Arithmetic,Average,4,False,False,False,,False,,
Average - Class 05,Arithmetic,Average,5,False,False,False,,False,,
Average - Class 06,Arithmetic,Average,6,False,False,False,,False,,
Average - Class 07,Arithmetic,Average,7,False,False,False,,False,,
Average - Class 08,Arithmetic,Average,8,False,False,False,,False,,
Mixture & Alligation - Class 01,Arithmetic,Mixture & Alligation,1,False,False,False,,False,,
Mixture & Alligation - Class 02,Arithmetic,Mixture & Alligation,2,False,False,False,,False,,
Mixture & Alligation - Class 03,Arithmetic,Mixture & Alligation,3,False,False,False,,False,,
Mixture & Alligation - Class 04,Arithmetic,Mixture & Alligation,4,False,False,False,,False,,
Mixture & Alligation - Class 05,Arithmetic,Mixture & Alligation,5,False,False,False,,False,,
Mixture & Alligation - Class 06,Arithmetic,Mixture & Alligation,6,False,False,False,,False,,
Mixture & Alligation - Class 07,Arithmetic,Mixture & Alligation,7,False,False,False,,False,,
Mixture & Alligation - Class 08,Arithmetic,Mixture & Alligation,8,False,False,False,,False,,
Mixture & Alligation - Class 09,Arithmetic,Mixture & Alligation,9,False,False,False,,False,,
Mixture & Alligation - Class 10,Arithmetic,Mixture & Alligation,10,False,False,False,,False,,
Mixture & Alligation - Class 11,Arithmetic,Mixture & Alligation,11,False,False,False,,False,,
Mixture & Alligation - Class 12,Arithmetic,Mixture & Alligation,12,False,False,False,,False,,
Mixture & Alligation - Class 13,Arithmetic,Mixture & Alligation,13,False,False,False,,False,,
Mixture & Alligation - Class 14,Arithmetic,Mixture & Alligation,14,False,False,False,,False,,
Partnership - Class 01,Arithmetic,Partnership,1,False,False,False,,False,,
Partnership - Class 02,Arithmetic,Partnership,2,False,False,False,,False,,
Partnership - Class 03,Arithmetic,Partnership,3,False,False,False,,False,,
Partnership - Class 04,Arithmetic,Partnership,4,False,False,False,,False,,
Problems on Ages - Class 01,Arithmetic,Problems on Ages,1,False,False,False,,False,,
Problems on Ages - Class 02,Arithmetic,Problems on Ages,2,False,False,False,,False,,
Problems on Ages - Class 03,Arithmetic,Problems on Ages,3,False,False,False,,False,,
Time & Work - Class 01,Arithmetic,Time & Work,1,False,False,False,,False,,
Time & Work - Class 02,Arithmetic,Time & Work,2,False,False,False,,False,,
Time & Work - Class 03,Arithmetic,Time & Work,3,False,False,False,,False,,
Time & Work - Class 04,Arithmetic,Time & Work,4,False,False,False,,False,,
Time & Work - Class 05,Arithmetic,Time & Work,5,False,False,False,,False,,
Time & Work - Class 06,Arithmetic,Time & Work,6,False,False,False,,False,,
Time & Work - Class 07,Arithmetic,Time & Work,7,False,False,False,,False,,
Time & Work - Class 08,Arithmetic,Time & Work,8,False,False,False,,False,,
Time & Work - Class 09,Arithmetic,Time & Work,9,False,False,False,,False,,
Time & Work - Class 10,Arithmetic,Time & Work,10,False,False,False,,False,,
Time & Work - Class 11,Arithmetic,Time & Work,11,False,False,False,,False,,
Time & Work - Class 12,Arithmetic,Time & Work,12,False,False,False,,False,,
Time & Work - Class 13,Arithmetic,Time & Work,13,False,False,False,,False,,
Time & Work - Class 14,Arithmetic,Time & Work,14,False,False,False,,False,,
Time & Work - Class 15,Arithmetic,Time & Work,15,False,False,False,,False,,
Pipe & Cistern - Class 01,Arithmetic,Pipe & Cistern,1,False,False,False,,False,,
Pipe & Cistern - Class 02,Arithmetic,Pipe & Cistern,2,False,False,False,,False,,
Pipe & Cistern - Class 03,Arithmetic,Pipe & Cistern,3,False,False,False,,False,,
Pipe & Cistern - Class 04,Arithmetic,Pipe & Cistern,4,False,False,False,,False,,
Pipe & Cistern - Class 05,Arithmetic,Pipe & Cistern,5,False,False,False,,False,,
"Time, Speed & Distance - Class 01",Arithmetic,"Time, Speed & Distance",1,False,False,False,,False,,
"Time, Speed & Distance - Class 02",Arithmetic,"Time, Speed & Distance",2,False,False,False,,False,,
"Time, Speed & Distance - Class 03",Arithmetic,"Time, Speed & Distance",3,False,False,False,,False,,
"Time, Speed & Distance - Class 04",Arithmetic,"Time, Speed & Distance",4,False,False,False,,False,,
"Time, Speed & Distance - Class 05",Arithmetic,"Time, Speed & Distance",5,False,False,False,,False,,
"Time, Speed & Distance - Class 06",Arithmetic,"Time, Speed & Distance",6,False,False,False,,False,,
"Time, Speed & Distance - Class 07",Arithmetic,"Time, Speed & Distance",7,False,False,False,,False,,
"Time, Speed & Distance - Class 08",Arithmetic,"Time, Speed & Distance",8,False,False,False,,False,,
"Time, Speed & Distance - Class 09",Arithmetic,"Time, Speed & Distance",9,False,False,False,,False,,
"Time, Speed & Distance - Class 10",Arithmetic,"Time, Speed & Distance",10,False,False,False,,False,,
"Time, Speed & Distance - Class 11",Arithmetic,"Time, Speed & Distance",11,False,False,False,,False,,
"Time, Speed & Distance - Class 12",Arithmetic,"Time, Speed & Distance",12,False,False,False,,False,,
"Time, Speed & Distance - Class 13",Arithmetic,"Time, Speed & Distance",13,False,False,False,,False,,
"Time, Speed & Distance - Class 14",Arithmetic,"Time, Speed & Distance",14,False,False,False,,False,,
"Time, Speed & Distance - Class 15",Arithmetic,"Time, Speed & Distance",15,False,False,False,,False,,
"Time, Speed & Distance - Class 16",Arithmetic,"Time, Speed & Distance",16,False,False,False,,False,,
"Time, Speed & Distance - Class 17",Arithmetic,"Time, Speed & Distance",17,False,False,False,,False,,
Trains - Class 01,Arithmetic,Trains,1,False,False,False,,False,,
Trains - Class 02,Arithmetic,Trains,2,False,False,False,,False,,
Trains - Class 03,Arithmetic,Trains,3,False,False,False,,False,,
Trains - Class 04,Arithmetic,Trains,4,False,False,False,,False,,
Boats & Streams - Class 01,Arithmetic,Boats & Streams,1,False,False,False,,False,,
Boats & Streams - Class 02,Arithmetic,Boats & Streams,2,False,False,False,,False,,
Boats & Streams - Class 03,Arithmetic,Boats & Streams,3,False,False,False,,False,,
Race - Class 01,Arithmetic,Race,1,False,False,False,,False,,
Race - Class 02,Arithmetic,Race,2,False,False,False,,False,,
Race - Class 03,Arithmetic,Race,3,False,False,False,,False,,
Dishonest Shopkeeper & Misc. - Class 01,Arithmetic,Dishonest Shopkeeper & Misc.,1,False,False,False,,False,,
Dishonest Shopkeeper & Misc. - Class 02,Arithmetic,Dishonest Shopkeeper & Misc.,2,False,False,False,,False,,
Dishonest Shopkeeper & Misc. - Class 03,Arithmetic,Dishonest Shopkeeper & Misc.,3,False,False,False,,False,,
Installment - Class 01,Arithmetic,Installment,1,False,False,False,,False,,
Algebra - Class 01,Advanced Maths,Algebra,1,False,False,False,,False,,
Algebra - Class 02,Advanced Maths,Algebra,2,False,False,False,,False,,
Algebra - Class 03,Advanced Maths,Algebra,3,False,False,False,,False,,
Algebra - Class 04,Advanced Maths,Algebra,4,False,False,False,,False,,
Algebra - Class 05,Advanced Maths,Algebra,5,False,False,False,,False,,
Algebra - Class 06,Advanced Maths,Algebra,6,False,False,False,,False,,
Algebra - Class 07,Advanced Maths,Algebra,7,False,False,False,,False,,
Algebra - Class 08,Advanced Maths,Algebra,8,False,False,False,,False,,
Algebra - Class 09,Advanced Maths,Algebra,9,False,False,False,,False,,
Algebra - Class 10,Advanced Maths,Algebra,10,False,False,False,,False,,
Algebra - Class 11,Advanced Maths,Algebra,11,False,False,False,,False,,
Algebra - Class 12,Advanced Maths,Algebra,12,False,False,False,,False,,
Algebra - Class 13,Advanced Maths,Algebra,13,False,False,False,,False,,
Algebra - Class 14,Advanced Maths,Algebra,14,False,False,False,,False,,
Algebra - Class 15,Advanced Maths,Algebra,15,False,False,False,,False,,
Algebra - Class 16,Advanced Maths,Algebra,16,False,False,False,,False,,
Algebra - Class 17,Advanced Maths,Algebra,17,False,False,False,,False,,
Algebra - Class 18,Advanced Maths,Algebra,18,False,False,False,,False,,
Algebra - Class 19,Advanced Maths,Algebra,19,False,False,False,,False,,
Algebra - Class 20,Advanced Maths,Algebra,20,False,False,False,,False,,
Algebra - Class 21,Advanced Maths,Algebra,21,False,False,False,,False,,
Algebra - Class 22,Advanced Maths,Algebra,22,False,False,False,,False,,
Algebra - Class 23,Advanced Maths,Algebra,23,False,False,False,,False,,
Algebra - Class 24,Advanced Maths,Algebra,24,False,False,False,,False,,
Algebra - Class 25,Advanced Maths,Algebra,25,False,False,False,,False,,
Algebra - Class 26,Advanced Maths,Algebra,26,False,False,False,,False,,
Algebra - Class 27,Advanced Maths,Algebra,27,False,False,False,,False,,
Algebra - Class 28,Advanced Maths,Algebra,28,False,False,False,,False,,
Algebra - Class 29,Advanced Maths,Algebra,29,False,False,False,,False,,
Algebra - Class 30,Advanced Maths,Algebra,30,False,False,False,,False,,
Quadratic Equations - Class 01,Advanced Maths,Quadratic Equations,1,False,False,False,,False,,
Quadratic Equations - Class 02,Advanced Maths,Quadratic Equations,2,False,False,False,,False,,
Quadratic Equations - Class 03,Advanced Maths,Quadratic Equations,3,False,False,False,,False,,
Quadratic Equations - Class 04,Advanced Maths,Quadratic Equations,4,False,False,False,,False,,
Geometry - Class 01,Advanced Maths,Geometry,1,False,False,False,,False,,
Geometry - Class 02,Advanced Maths,Geometry,2,False,False,False,,False,,
Geometry - Class 03,Advanced Maths,Geometry,3,False,False,False,,False,,
Geometry - Class 04,Advanced Maths,Geometry,4,False,False,False,,False,,
Geometry - Class 05,Advanced Maths,Geometry,5,False,False,False,,False,,
Geometry - Class 06,Advanced Maths,Geometry,6,False,False,False,,False,,
Geometry - Class 07,Advanced Maths,Geometry,7,False,False,False,,False,,
Geometry - Class 08,Advanced Maths,Geometry,8,False,False,False,,False,,
Geometry - Class 09,Advanced Maths,Geometry,9,False,False,False,,False,,
Geometry - Class 10,Advanced Maths,Geometry,10,False,False,False,,False,,
Geometry - Class 11,Advanced Maths,Geometry,11,False,False,False,,False,,
Geometry - Class 12,Advanced Maths,Geometry,12,False,False,False,,False,,
Geometry - Class 13,Advanced Maths,Geometry,13,False,False,False,,False,,
Geometry - Class 14,Advanced Maths,Geometry,14,False,False,False,,False,,
Geometry - Class 15,Advanced Maths,Geometry,15,False,False,False,,False,,
Geometry - Class 16,Advanced Maths,Geometry,16,False,False,False,,False,,
Geometry - Class 17,Advanced Maths,Geometry,17,False,False,False,,False,,
Geometry - Class 18,Advanced Maths,Geometry,18,False,False,False,,False,,
Geometry - Class 19,Advanced Maths,Geometry,19,False,False,False,,False,,
Geometry - Class 20,Advanced Maths,Geometry,20,False,False,False,,False,,
Geometry - Class 21,Advanced Maths,Geometry,21,False,False,False,,False,,
Geometry - Class 22,Advanced Maths,Geometry,22,False,False,False,,False,,
Geometry - Class 23,Advanced Maths,Geometry,23,False,False,False,,False,,
Geometry - Class 24,Advanced Maths,Geometry,24,False,False,False,,False,,
Geometry - Class 25,Advanced Maths,Geometry,25,False,False,False,,False,,
Geometry - Class 26,Advanced Maths,Geometry,26,False,False,False,,False,,
Geometry - Class 27,Advanced Maths,Geometry,27,False,False,False,,False,,
Geometry - Class 28,Advanced Maths,Geometry,28,False,False,False,,False,,
Geometry - Class 29,Advanced Maths,Geometry,29,False,False,False,,False,,
Geometry - Class 30,Advanced Maths,Geometry,30,False,False,False,,False,,
Geometry - Class 31,Advanced Maths,Geometry,31,False,False,False,,False,,
Geometry - Class 32,Advanced Maths,Geometry,32,False,False,False,,False,,
Geometry - Class 33,Advanced Maths,Geometry,33,False,False,False,,False,,
Geometry - Class 34,Advanced Maths,Geometry,34,False,False,False,,False,,
Geometry - Class 35,Advanced Maths,Geometry,35,False,False,False,,False,,
Geometry - Class 36,Advanced Maths,Geometry,36,False,False,False,,False,,
Geometry - Class 37,Advanced Maths,Geometry,37,False,False,False,,False,,
Geometry - Class 38,Advanced Maths,Geometry,38,False,False,False,,False,,
Geometry - Class 39,Advanced Maths,Geometry,39,False,False,False,,False,,
Geometry - Class 40,Advanced Maths,Geometry,40,False,False,False,,False,,
Geometry - Class 41,Advanced Maths,Geometry,41,False,False,False,,False,,
Geometry - Class 42,Advanced Maths,Geometry,42,False,False,False,,False,,
Geometry - Class 43,Advanced Maths,Geometry,43,False,False,False,,False,,
Geometry - Class 44,Advanced Maths,Geometry,44,False,False,False,,False,,
Geometry - Class 45,Advanced Maths,Geometry,45,False,False,False,,False,,
Geometry - Class 46,Advanced Maths,Geometry,46,False,False,False,,False,,
Geometry - Class 47,Advanced Maths,Geometry,47,False,False,False,,False,,
Geometry - Class 48,Advanced Maths,Geometry,48,False,False,False,,False,,
Geometry - Class 49,Advanced Maths,Geometry,49,False,False,False,,False,,
Geometry - Class 50,Advanced Maths,Geometry,50,False,False,False,,False,,
Geometry - Class 51,Advanced Maths,Geometry,51,False,False,False,,False,,
Geometry - Class 52,Advanced Maths,Geometry,52,False,False,False,,False,,
Geometry - Class 53,Advanced Maths,Geometry,53,False,False,False,,False,,
Geometry - Class 54,Advanced Maths,Geometry,54,False,False,False,,False,,
Geometry - Class 55,Advanced Maths,Geometry,55,False,False,False,,False,,
Geometry - Class 56,Advanced Maths,Geometry,56,False,False,False,,False,,
Geometry - Class 57,Advanced Maths,Geometry,57,False,False,False,,False,,
Geometry - Class 58,Advanced Maths,Geometry,58,False,False,False,,False,,
Geometry - Class 59,Advanced Maths,Geometry,59,False,False,False,,False,,
Geometry - Class 60,Advanced Maths,Geometry,60,False,False,False,,False,,
Geometry - Class 61,Advanced Maths,Geometry,61,False,False,False,,False,,
Geometry - Class 62,Advanced Maths,Geometry,62,False,False,False,,False,,
Geometry - Class 63,Advanced Maths,Geometry,63,False,False,False,,False,,
Geometry - Class 64,Advanced Maths,Geometry,64,False,False,False,,False,,
Geometry - Class 65,Advanced Maths,Geometry,65,False,False,False,,False,,
Geometry - Class 66,Advanced Maths,Geometry,66,False,False,False,,False,,
Geometry - Class 67,Advanced Maths,Geometry,67,False,False,False,,False,,
Geometry - Class 68,Advanced Maths,Geometry,68,False,False,False,,False,,
Geometry - Class 69,Advanced Maths,Geometry,69,False,False,False,,False,,
Geometry - Class 70,Advanced Maths,Geometry,70,False,False,False,,False,,
Geometry - Class 71,Advanced Maths,Geometry,71,False,False,False,,False,,
Geometry - Class 72,Advanced Maths,Geometry,72,False,False,False,,False,,
Geometry - Class 73,Advanced Maths,Geometry,73,False,False,False,,False,,
2D Mensuration - Class 01,Advanced Maths,2D Mensuration,1,False,False,False,,False,,
2D Mensuration - Class 02,Advanced Maths,2D Mensuration,2,False,False,False,,False,,
2D Mensuration - Class 03,Advanced Maths,2D Mensuration,3,False,False,False,,False,,
2D Mensuration - Class 04,Advanced Maths,2D Mensuration,4,False,False,False,,False,,
2D Mensuration - Class 05,Advanced Maths,2D Mensuration,5,False,False,False,,False,,
2D Mensuration - Class 06,Advanced Maths,2D Mensuration,6,False,False,False,,False,,
2D Mensuration - Class 07,Advanced Maths,2D Mensuration,7,False,False,False,,False,,
2D Mensuration - Class 08,Advanced Maths,2D Mensuration,8,False,False,False,,False,,
2D Mensuration - Class 09,Advanced Maths,2D Mensuration,9,False,False,False,,False,,
2D Mensuration - Class 10,Advanced Maths,2D Mensuration,10,False,False,False,,False,,
2D Mensuration - Class 11,Advanced Maths,2D Mensuration,11,False,False,False,,False,,
2D Mensuration - Class 12,Advanced Maths,2D Mensuration,12,False,False,False,,False,,
2D Mensuration - Class 13,Advanced Maths,2D Mensuration,13,False,False,False,,False,,
2D Mensuration - Class 14,Advanced Maths,2D Mensuration,14,False,False,False,,False,,
2D Mensuration - Class 15,Advanced Maths,2D Mensuration,15,False,False,False,,False,,
3D Mensuration - Class 01,Advanced Maths,3D Mensuration,1,False,False,False,,False,,
3D Mensuration - Class 02,Advanced Maths,3D Mensuration,2,False,False,False,,False,,
3D Mensuration - Class 03,Advanced Maths,3D Mensuration,3,False,False,False,,False,,
3D Mensuration - Class 04,Advanced Maths,3D Mensuration,4,False,False,False,,False,,
3D Mensuration - Class 05,Advanced Maths,3D Mensuration,5,False,False,False,,False,,
3D Mensuration - Class 06,Advanced Maths,3D Mensuration,6,False,False,False,,False,,
3D Mensuration - Class 07,Advanced Maths,3D Mensuration,7,False,False,False,,False,,
3D Mensuration - Class 08,Advanced Maths,3D Mensuration,8,False,False,False,,False,,
3D Mensuration - Class 09,Advanced Maths,3D Mensuration,9,False,False,False,,False,,
3D Mensuration - Class 10,Advanced Maths,3D Mensuration,10,False,False,False,,False,,
3D Mensuration - Class 11,Advanced Maths,3D Mensuration,11,False,False,False,,False,,
3D Mensuration - Class 12,Advanced Maths,3D Mensuration,12,False,False,False,,False,,
3D Mensuration - Class 13,Advanced Maths,3D Mensuration,13,False,False,False,,False,,
3D Mensuration - Class 14,Advanced Maths,3D Mensuration,14,False,False,False,,False,,
3D Mensuration - Class 15,Advanced Maths,3D Mensuration,15,False,False,False,,False,,
3D Mensuration - Class 16,Advanced Maths,3D Mensuration,16,False,False,False,,False,,
3D Mensuration - Class 17,Advanced Maths,3D Mensuration,17,False,False,False,,False,,
3D Mensuration - Class 18,Advanced Maths,3D Mensuration,18,False,False,False,,False,,
3D Mensuration - Class 19,Advanced Maths,3D Mensuration,19,False,False,False,,False,,
3D Mensuration - Class 20,Advanced Maths,3D Mensuration,20,False,False,False,,False,,
3D Mensuration - Class 21,Advanced Maths,3D Mensuration,21,False,False,False,,False,,
3D Mensuration - Class 22,Advanced Maths,3D Mensuration,22,False,False,False,,False,,
3D Mensuration - Class 23,Advanced Maths,3D Mensuration,23,False,False,False,,False,,
Trigonometry - Class 01,Advanced Maths,Trigonometry,1,False,False,False,,False,,
Trigonometry - Class 02,Advanced Maths,Trigonometry,2,False,False,False,,False,,
Trigonometry - Class 03,Advanced Maths,Trigonometry,3,False,False,False,,False,,
Trigonometry - Class 04,Advanced Maths,Trigonometry,4,False,False,False,,False,,
Trigonometry - Class 05,Advanced Maths,Trigonometry,5,False,False,False,,False,,
Trigonometry - Class 06,Advanced Maths,Trigonometry,6,False,False,False,,False,,
Trigonometry - Class 07,Advanced Maths,Trigonometry,7,False,False,False,,False,,
Trigonometry - Class 08,Advanced Maths,Trigonometry,8,False,False,False,,False,,
Trigonometry - Class 09,Advanced Maths,Trigonometry,9,False,False,False,,False,,
Trigonometry - Class 10,Advanced Maths,Trigonometry,10,False,False,False,,False,,
Trigonometry - Class 11,Advanced Maths,Trigonometry,11,False,False,False,,False,,
Trigonometry - Class 12,Advanced Maths,Trigonometry,12,False,False,False,,False,,
Trigonometry - Class 13,Advanced Maths,Trigonometry,13,False,False,False,,False,,
Trigonometry - Class 14,Advanced Maths,Trigonometry,14,False,False,False,,False,,
Trigonometry - Class 15,Advanced Maths,Trigonometry,15,False,False,False,,False,,
Trigonometry - Class 16,Advanced Maths,Trigonometry,16,False,False,False,,False,,
Trigonometry - Class 17,Advanced Maths,Trigonometry,17,False,False,False,,False,,
Trigonometry - Class 18,Advanced Maths,Trigonometry,18,False,False,False,,False,,
Trigonometry - Class 19,Advanced Maths,Trigonometry,19,False,False,False,,False,,
Trigonometry - Class 20,Advanced Maths,Trigonometry,20,False,False,False,,False,,
Trigonometry - Class 21,Advanced Maths,Trigonometry,21,False,False,False,,False,,
Trigonometry - Class 22,Advanced Maths,Trigonometry,22,False,False,False,,False,,
Trigonometry - Class 23,Advanced Maths,Trigonometry,23,False,False,False,,False,,
Trigonometry - Class 24,Advanced Maths,Trigonometry,24,False,False,False,,False,,
Trigonometry - Class 25,Advanced Maths,Trigonometry,25,False,False,False,,False,,
Heights & Distances - Class 01,Advanced Maths,Heights & Distances,1,False,False,False,,False,,
Heights & Distances - Class 02,Advanced Maths,Heights & Distances,2,False,False,False,,False,,
Heights & Distances - Class 03,Advanced Maths,Heights & Distances,3,False,False,False,,False,,
Heights & Distances - Class 04,Advanced Maths,Heights & Distances,4,False,False,False,,False,,
Coordinate Geometry - Class 01,Advanced Maths,Coordinate Geometry,1,False,False,False,,False,,
Coordinate Geometry - Class 02,Advanced Maths,Coordinate Geometry,2,False,False,False,,False,,
Coordinate Geometry - Class 03,Advanced Maths,Coordinate Geometry,3,False,False,False,,False,,
Coordinate Geometry - Class 04,Advanced Maths,Coordinate Geometry,4,False,False,False,,False,,
Coordinate Geometry - Class 05,Advanced Maths,Coordinate Geometry,5,False,False,False,,False,,
Coordinate Geometry - Class 06,Advanced Maths,Coordinate Geometry,6,False,False,False,,False,,
Coordinate Geometry - Class 07,Advanced Maths,Coordinate Geometry,7,False,False,False,,False,,
Coordinate Geometry - Class 08,Advanced Maths,Coordinate Geometry,8,False,False,False,,False,,
Coordinate Geometry - Class 09,Advanced Maths,Coordinate Geometry,9,False,False,False,,False,,
Coordinate Geometry - Class 10,Advanced Maths,Coordinate Geometry,10,False,False,False,,False,,
Probability - Class 01,Advanced Maths,Probability,1,False,False,False,,False,,
Probability - Class 02,Advanced Maths,Probability,2,False,False,False,,False,,
Probability - Class 03,Advanced Maths,Probability,3,False,False,False,,False,,
Permutations & Combinations - Class 01,Advanced Maths,Permutations & Combinations,1,False,False,False,,False,,
Statistics - Class 01,Advanced Maths,Statistics,1,False,False,False,,False,,
Statistics - Class 02,Advanced Maths,Statistics,2,False,False,False,,False,,
Statistics - Class 03,Advanced Maths,Statistics,3,False,False,False,,False,,
Data Interpretation - Class 01,Advanced Maths,Data Interpretation,1,False,False,False,,False,,
Data Interpretation - Class 02,Advanced Maths,Data Interpretation,2,False,False,False,,False,,
`;
