// Automatically generated default CSV data for GK, Reasoning, and English subjects

const defaultGkCsv = `Lecture,Phase,Topic,Class No,Completed,Revision 1,Revision 2,Questions Solved,Weak Topic,Date Completed,Notes
Stone Age,Ancient History,Ancient History,1,False,False,False,,False,,
Indus civilisation,Ancient History,Ancient History,2,False,False,False,,False,,
Vedic age,Ancient History,Ancient History,3,False,False,False,,False,,
Buddhism and Jainism,Ancient History,Ancient History,4,False,False,False,,False,,
Mahajanapadas,Ancient History,Ancient History,5,False,False,False,,False,,
Mauryan Empire,Ancient History,Ancient History,6,False,False,False,,False,,
Post Mauryan Dynasties,Ancient History,Ancient History,7,False,False,False,,False,,
Sangam age,Ancient History,Ancient History,8,False,False,False,,False,,
Guptas and Chalukyas,Ancient History,Ancient History,9,False,False,False,,False,,
Post Gupta Dynasties,Ancient History,Ancient History,10,False,False,False,,False,,
Tripartite struggle and Chola,Ancient History,Ancient History,11,False,False,False,,False,,
Advent of Europeans,Modern History,Modern History,1,False,False,False,,False,,
Maratha Kingdom,Modern History,Modern History,2,False,False,False,,False,,
Socio religious reforms,Modern History,Modern History,3,False,False,False,,False,,
1857 revolt,Modern History,Modern History,4,False,False,False,,False,,
Indian national Congress,Modern History,Modern History,5,False,False,False,,False,,
Bengal partition,Modern History,Modern History,6,False,False,False,,False,,
Emergence of Gandhi,Modern History,Modern History,7,False,False,False,,False,,
"Simon com. & civil disobedience movement",Modern History,Modern History,8,False,False,False,,False,,
Quit India movement,Modern History,Modern History,9,False,False,False,,False,,
Bhakti and Sufi movement,Modern History,Modern History,10,False,False,False,,False,,
Delhi Sultanate,Medieval History,Medieval History,1,False,False,False,,False,,
VijayNagar & Bahamani,Medieval History,Medieval History,2,False,False,False,,False,,
Mughal Empire,Medieval History,Medieval History,3,False,False,False,,False,,
Solar system,Geography,Geography,1,False,False,False,,False,,
Latitude and longitude,Geography,Geography,2,False,False,False,,False,,
Interior of earth,Geography,Geography,3,False,False,False,,False,,
Continents & oceans,Geography,Geography,4,False,False,False,,False,,
Geomorphology and landforms,Geography,Geography,5,False,False,False,,False,,
Atmosphere and water,Geography,Geography,6,False,False,False,,False,,
"Wind, cyclone & currents",Geography,Geography,7,False,False,False,,False,,
India and its location,Geography,Geography,8,False,False,False,,False,,
Himalayas,Geography,Geography,9,False,False,False,,False,,
Peninsular Plateau,Geography,Geography,10,False,False,False,,False,,
Northern plains & islands,Geography,Geography,11,False,False,False,,False,,
Himalayan river,Geography,Geography,12,False,False,False,,False,,
Peninsula river,Geography,Geography,13,False,False,False,,False,,
Climate of India,Geography,Geography,14,False,False,False,,False,,
Forest and grassland,Geography,Geography,15,False,False,False,,False,,
Agriculture,Geography,Geography,16,False,False,False,,False,,
Minerals,Geography,Geography,17,False,False,False,,False,,
"Dams, lakes & waterfalls",Geography,Geography,18,False,False,False,,False,,
National Park and biosphere reserves,Geography,Geography,19,False,False,False,,False,,
Making of constitution,Polity,Polity,1,False,False,False,,False,,
Features of Indian const.,Polity,Polity,2,False,False,False,,False,,
Integration and merger of states,Polity,Polity,3,False,False,False,,False,,
Fundamental rights,Polity,Polity,4,False,False,False,,False,,
DPSPs & fundamental duties,Polity,Polity,5,False,False,False,,False,,
President & vice president,Polity,Polity,6,False,False,False,,False,,
PM & council of ministers,Polity,Polity,7,False,False,False,,False,,
Parliament,Polity,Polity,8,False,False,False,,False,,
State legislature,Polity,Polity,9,False,False,False,,False,,
Emergency,Polity,Polity,10,False,False,False,,False,,
Judiciary,Polity,Polity,11,False,False,False,,False,,
Panchayat and municipalities,Polity,Polity,12,False,False,False,,False,,
Constitutional bodies,Polity,Polity,13,False,False,False,,False,,
"Acts (Charter, Indian council's Act, etc)",Polity,Polity,14,False,False,False,,False,,
Important amendments,Polity,Polity,15,False,False,False,,False,,
Cell,Biology,Biology,1,False,False,False,,False,,
Tissue,Biology,Biology,2,False,False,False,,False,,
Kingdom,Biology,Biology,3,False,False,False,,False,,
Nervous system,Biology,Biology,4,False,False,False,,False,,
Hormones & glands,Biology,Biology,5,False,False,False,,False,,
Reproduction,Biology,Biology,6,False,False,False,,False,,
Digestive system,Biology,Biology,7,False,False,False,,False,,
Respiratory system,Biology,Biology,8,False,False,False,,False,,
Circulatory system,Biology,Biology,9,False,False,False,,False,,
Excretory system,Biology,Biology,10,False,False,False,,False,,
Nutrients & vitamins,Biology,Biology,11,False,False,False,,False,,
Diseases,Biology,Biology,12,False,False,False,,False,,
"Heredity, bones & joints",Biology,Biology,13,False,False,False,,False,,
Matter,Chemistry,Chemistry,1,False,False,False,,False,,
Atom and its structure,Chemistry,Chemistry,2,False,False,False,,False,,
Periodic table,Chemistry,Chemistry,3,False,False,False,,False,,
Chemical reactions,Chemistry,Chemistry,4,False,False,False,,False,,
Metal and non-metal,Chemistry,Chemistry,5,False,False,False,,False,,
Acid base & salt,Chemistry,Chemistry,6,False,False,False,,False,,
Carbon and its compound,Chemistry,Chemistry,7,False,False,False,,False,,
Motion,Physics,Physics,1,False,False,False,,False,,
Gravitation & work done,Physics,Physics,2,False,False,False,,False,,
Sound,Physics,Physics,3,False,False,False,,False,,
Light,Physics,Physics,4,False,False,False,,False,,
Human eye and vision,Physics,Physics,5,False,False,False,,False,,
Electricity,Physics,Physics,6,False,False,False,,False,,
Magnetic effect of electric current,Physics,Physics,7,False,False,False,,False,,
Basics of economy,Economics,Economics,1,False,False,False,,False,,
Demand & supply,Economics,Economics,2,False,False,False,,False,,
National income,Economics,Economics,3,False,False,False,,False,,
Inflation and unemployment,Economics,Economics,4,False,False,False,,False,,
Budget and taxation,Economics,Economics,5,False,False,False,,False,,
Money and banking,Economics,Economics,6,False,False,False,,False,,
Monetary policy,Economics,Economics,7,False,False,False,,False,,
Balance of payment,Economics,Economics,8,False,False,False,,False,,
Poverty,Economics,Economics,9,False,False,False,,False,,
Five year plan & IPR,Economics,Economics,10,False,False,False,,False,,
Classical dance,Static GK,Static GK,1,False,False,False,,False,,
Folk dance,Static GK,Static GK,2,False,False,False,,False,,
Census,Static GK,Static GK,3,False,False,False,,False,,
Festival,Static GK,Static GK,4,False,False,False,,False,,
Musical instruments,Static GK,Static GK,5,False,False,False,,False,,
Gharanas,Static GK,Static GK,6,False,False,False,,False,,
Organisations (National & International),Static GK,Static GK,7,False,False,False,,False,,
Books and authors,Static GK,Static GK,8,False,False,False,,False,,
Sports,Static GK,Static GK,9,False,False,False,,False,,
Important days,Static GK,Static GK,10,False,False,False,,False,,
Appointments,Current Affairs,Current Affairs,1,False,False,False,,False,,
Awards,Current Affairs,Current Affairs,2,False,False,False,,False,,
Index,Current Affairs,Current Affairs,3,False,False,False,,False,,
Schemes,Current Affairs,Current Affairs,4,False,False,False,,False,,
Military exercises,Current Affairs,Current Affairs,5,False,False,False,,False,,
Books & authors,Current Affairs,Current Affairs,6,False,False,False,,False,,
Science & technology,Current Affairs,Current Affairs,7,False,False,False,,False,,
Sports,Current Affairs,Current Affairs,8,False,False,False,,False,,
Bills,Current Affairs,Current Affairs,9,False,False,False,,False,,
Budget & economic survey,Current Affairs,Current Affairs,10,False,False,False,,False,,`;

const defaultReasoningCsv = `Lecture,Phase,Topic,Class No,Completed,Revision 1,Revision 2,Questions Solved,Weak Topic,Date Completed,Notes
Analogy,Time + Practice,Time + Practice,1,False,False,False,,False,,
Odd one out,Time + Practice,Time + Practice,2,False,False,False,,False,,
Coding decoding,Time + Practice,Time + Practice,3,False,False,False,,False,,
Series,Time + Practice,Time + Practice,4,False,False,False,,False,,
Syllogism,Easy Marks,Easy Marks,1,False,False,False,,False,,
Direction and distance,Easy Marks,Easy Marks,2,False,False,False,,False,,
Mathematical operations,Easy Marks,Easy Marks,3,False,False,False,,False,,
Paper cut/fold,Easy Marks,Easy Marks,4,False,False,False,,False,,
Mirror image,Easy Marks,Easy Marks,5,False,False,False,,False,,
Embedded figure,Easy Marks,Easy Marks,6,False,False,False,,False,,
Sitting arrangement,Technique + Practice,Technique + Practice,1,False,False,False,,False,,
Order and ranking,Technique + Practice,Technique + Practice,2,False,False,False,,False,,
Blood relation,Technique + Practice,Technique + Practice,3,False,False,False,,False,,
Analytical reasoning,Technique + Practice,Technique + Practice,4,False,False,False,,False,,
Calendar,Only Technique,Only Technique,1,False,False,False,,False,,
Inequality,Only Technique,Only Technique,2,False,False,False,,False,,
Counting of figures,Only Technique,Only Technique,3,False,False,False,,False,,
Cube and Dice,Only Technique,Only Technique,4,False,False,False,,False,,
Pair formation,Only Technique,Only Technique,5,False,False,False,,False,,`;

const defaultEnglishCsv = `Lecture,Phase,Topic,Class No,Completed,Revision 1,Revision 2,Questions Solved,Weak Topic,Date Completed,Notes
Tenses,Grammar,Grammar,1,False,False,False,,False,,
Nouns,Grammar,Grammar,2,False,False,False,,False,,
Pronouns,Grammar,Grammar,3,False,False,False,,False,,
Adjectives,Grammar,Grammar,4,False,False,False,,False,,
Adverbs,Grammar,Grammar,5,False,False,False,,False,,
Conjunctions,Grammar,Grammar,6,False,False,False,,False,,
Verb,Grammar,Grammar,7,False,False,False,,False,,
Prepositions,Grammar,Grammar,8,False,False,False,,False,,
Voice,Grammar,Grammar,9,False,False,False,,False,,
Narration/Speech,Grammar,Grammar,10,False,False,False,,False,,
Conditionals,Grammar,Grammar,11,False,False,False,,False,,
Subject Verb Agreement,Grammar,Grammar,12,False,False,False,,False,,
Synonyms,Vocabulary,Vocabulary,1,False,False,False,,False,,
Antonyms,Vocabulary,Vocabulary,2,False,False,False,,False,,
OWS,Vocabulary,Vocabulary,3,False,False,False,,False,,
Idioms,Vocabulary,Vocabulary,4,False,False,False,,False,,
Homonyms,Vocabulary,Vocabulary,5,False,False,False,,False,,
Phrasal Verb,Vocabulary,Vocabulary,6,False,False,False,,False,,
Fixed Preposition,Vocabulary,Vocabulary,7,False,False,False,,False,,
Collocation,Vocabulary,Vocabulary,8,False,False,False,,False,,
Error detection,Practice,Practice,1,False,False,False,,False,,
Blanks,Practice,Practice,2,False,False,False,,False,,
Sentence improvement,Practice,Practice,3,False,False,False,,False,,
Direct/Indirect,Practice,Practice,4,False,False,False,,False,,
Active/Passive,Practice,Practice,5,False,False,False,,False,,
Spelling error,Practice,Practice,6,False,False,False,,False,,
Cloze Test,Comprehension,Comprehension,1,False,False,False,,False,,
Passage,Comprehension,Comprehension,2,False,False,False,,False,,
PQRS/ Sentence Rearrangement,Comprehension,Comprehension,3,False,False,False,,False,,`;

const defaultDailyCsv = `Lecture,Phase,Topic,Class No,Completed,Revision 1,Revision 2,Questions Solved,Weak Topic,Date Completed,Notes
Solve 1 Maths Sectional Mock,Mock practice,Mock Test,1,False,False,False,,False,,
Practice 50 GK Questions,Daily Practice,General Knowledge,2,False,False,False,,False,,
Revise English Vocab (50 words),Vocabulary,English,3,False,False,False,,False,,
Read Newspaper Editorial (30m),Reading skill,English,4,False,False,False,,False,,
Solve 1 Reasoning Mock,Mock practice,Reasoning,5,False,False,False,,False,,
Revise Core Formula Notes,Revision,Maths,6,False,False,False,,False,,
Analyze Mock Errors,Analysis,Mock Test,7,False,False,False,,False,,`;
